In [9]:
#Write a Python Program to Add Two Matrices?
import numpy as np
res=np.zeros([2,2],dtype=int)
a=[[2,3],[4,5]]
b=[[8,3],[1,9]]
for i in range(len(a)):
    for j in range(len(a[0])):
        res[i][j]=b[i][j]+a[i][j]
print(res)

[[10  6]
 [ 5 14]]


In [10]:
for i in res:
    print(i)

[10  6]
[ 5 14]


In [11]:
#Write a Python Program to Multiply Two Matrices?
a=[[2,3],[4,5]]
b=[[8,3],[1,9]]
mul=np.zeros([2,2],dtype=int)
for i in range(len(a)):
    for j in range(len(a[0])):
        mul[i][j]=b[i][j]*a[i][j]
print(mul)

[[16  9]
 [ 4 45]]


In [13]:
#Write a Python Program to Transpose a Matrix?
trans_mat=np.zeros([2,2],dtype=int)
a=[[2,3],[4,5]]
for i in range(len(a)):
    for j in range(len(a[0])):
        trans_mat[i][j]=a[j][i]
print(trans_mat)


[[2 4]
 [3 5]]


In [14]:
#Write a Python Program to Sort Words in Alphabetic Order?
s=input()
for i in range(len(s)):
    w=s.split()
w.sort()
print(w)


komal is best
['best', 'is', 'komal']


In [5]:
#Write a Python Program to Remove Punctuation From a String?
import re
s=input()
res=re.sub(r'[^\w\s]','',s)


komal is@#% nice and *humble


In [6]:
print(res)

komal is nice and humble
